services:
  db:
    image: postgres
    container_name: database
    hostname: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5

  redis:
    image: redis
    container_name: redis
    environment:
      REDIS_URL: redis://redis:6379/
    depends_on:  ['database']
    
  app:
    image: ruby
    container_name: ruby
    depends_on:
      db:
        condition: service_healthy
    command: bash -c 'bundle install && rake db:prepare && rake db:seed && ruby server.rb'
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
      - rebase_gems:/usr/local/bundle
    restart: on-failure 

  sidekiq:
    image: ruby
    container_name: sidekiq
    working_dir: /app
    volumes:
      - ./:/app
      - rebase_gems:/usr/local/bundle
    environment:
      REDIS_URL: redis://redis:6379
    depends_on: ['app', 'redis', 'database']
    tty: true
    stdin_open: true
    command: bash -c "bundle install && sidekiq -r './workers/import_worker.rb'"
    restart: on-failure
  
  sideboard:
    image: ruby
    container_name: sideboard
    working_dir: /app
    depends_on: ['sidekiq']
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
      - rebase_gems:/usr/local/bundle
    ports:
      - 3535:3535
    command: bash -c 'bundle && bundle exec rackup -o 0.0.0.0 -p 3535'

volumes:
  rebase_gems: