services:
  db:
    image: postgres
    container_name: database
    hostname: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass

  redis:
    image: redis
    container_name: redis
    environment:
      REDIS_URL: redis://redis:6379/
    depends_on: ['database']
  
  sidekiq:
    container_name: sidekiq
    image: ruby
    working_dir: /app
    volumes:
      - ./:/app
      - rebase_gems:/usr/local/bundle
    environment:
      REDIS_URL: redis://redis:6379
    depends_on: ['redis', 'database', 'app']
    #command: bash -c "bundle install && bundle exec sidekiq -r './workers/import_worker.rb'"
    stdin_open: true
    tty: true

  app:
    image: ruby
    container_name: ruby
    depends_on: ['database']
    stdin_open: true
    tty: true
    #command: bash -c 'bundle install && ruby server.rb'
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
      - rebase_gems:/usr/local/bundle
   
volumes:
  rebase_gems: