services:
  db:
    image: postgres
    container_name: postgres
    hostname: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    network_mode: "host"

  redis:
    image: redis
    container_name: redis
    network_mode: "host"

  app:
    image: ruby
    container_name: ruby
    depends_on: ['db']
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
      - rechallenge_gems:/usr/local/bundle
    network_mode: "host"
   
volumes:
  rechallenge_gems: